apiVersion: apps/v1

kind: Deployment
metadata:
  labels:
    k8s-app: mt-autocheckin
  name: mt-autocheckin
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: mt-autocheckin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: mt-autocheckin
    spec:
      containers:
      - name: mt-autocheckin
        image: bitwild/mt-autocheckin:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: MTEAM_USERNAME
          value: your_mteam_username
        - name: MTEAM_PASSWORD
          value: your_mteam_password
        - name: MTEAM_TOTP_SECRET
          value: your_mteam_totp_secret
        - name: SMTP_HOST
          value: your_smtp_host
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_USERNAME
          value: your_smtp_username
        - name: SMTP_PASSWORD
          value: your_smtp_password
        - name: TELEGRAM_BOT_TOKEN
          value: your_telegram_bot_token
        - name: TELEGRAM_CHAT_ID
          value: your_telegram_chat_id
        - name: FEISHU_BOT_TOKEN
          value: your_feishu_bot_token
        - name: NOTIFY_TYPE
          value: smtp
        - name: NOTIFY_EMAIL
          value: your_notify_email
        command: ["sh", "-c", "python MT-AutoCheckIn.py"]
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - "python MT-AutoCheckIn.py"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - pgrep
            - -f
            - "python MT-AutoCheckIn.py"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3

